### ISSUE TITLE
RDP module doesn't shows correct result

### ISSUE THREAD

**Issue by prismbreak** [Porchetta-Industries/CrackMapExec#766]
**Describe the bug**
When trying to log in with RDP module, it gives the following error:
![image](https://user-images.githubusercontent.com/50661527/228209813-2cad9881-5354-4cf3-8380-2c3266a28863.png)
But I can log in manually with the same creds:
![image](https://user-images.githubusercontent.com/50661527/228210270-212635df-7909-432f-9597-2902a9c73816.png)

**To Reproduce**

**Expected behavior**
It should output that I can log in or 'pwd3d!'

**Crackmapexec info**
 - OS: Kali 2022.4
 - Version of CME 5.4.0

**Comment by lavclash75** [comment]
hi i have the same issue how did you fixed  ?

**Comment by NeffIsBack** [comment]
Hi, there was a bug in the rdp protocol which got fixed with the commit d00a9bafeb0fc6df0718486ded5087b55b0bd50b.
As there was no official release since then it might be possible that your version does not have the bugfix if you downloaded crackmapexec via apt or pip (/pipx).
You can try to clone the repository and install it with `pipx install .`. That might solve your problem (and maybe was the original problem here).
